### ISSUE TITLE
Adapter löst immer neuen Anruf aus

### ISSUE THREAD

**Issue by mangel8** [Bettman66/ioBroker.doorio#46]
Hallo zusammen.

ich habe gestern den Adapter auf die aktuellste Version 2.1.3 aktualisiert. Seitdem habe ich das problem das wenn ich einen Anruf starte der adapter nichtmehr aufhört anzurufen. Wenn der Anruf beantwortet wird wird die Leitung gehalten und man kann das gespräch führen aber sobald man auflegt wird sofort über ctrl_tcp: handle_command:  cmd='dial' ein neuer Anruf gestartet. Legt man direkt auf wird auch sofort ein neuer Anruf ausgelöst.
Dasgnaze machte die Klingel gerade ziemlich nutzlos. 
Mit einem downgrade auf Version 2.1.0 tritt das verhalten nichtmehr auf.
2.1.1 lies sich nicht installieren und 2.1.2 hatte bei mir das gleiche Problem.

Vielen Dank schonmal für die Hilfe

Grüße Michael

username@10.0.0.44: {0/UDP/v4} 200 OK () [1 binding]
All 1 useragent registered successfully! (13 ms)

ctrl_tcp: handle_command:  cmd='dial', params:'0123456789', token=''
call: alloc with params laddr=10.0.0.40, af=AF_INET, use_rtp=1
call: use_video=0
call: connecting to 'sip:0123456789@10.0.0.44'..
call: SIP Progress: 100 Trying (/)
call: SIP Progress: 183 Session Progress (application/sdp)
call: stream start (active=0)
audio: Set audio encoder: PCMU 8000Hz 1ch
audio: start
alsa: reset: srate=8000, ch=1, num_frames=160, pcmfmt=S16_LE
alsa: recording started (default) format=S16LE
audio: source started with sample format S16LE
audio: Set audio decoder: PCMU 8000Hz 1ch
audio: start
alsa: reset: srate=8000, ch=1, num_frames=160, pcmfmt=S16_LE
alsa: playback started (default)
audio: player started with sample format S16LE
audio tx pipeline:        alsa ---> vumeter ---> PCMU
audio rx pipeline:        alsa <--- vumeter <--- PCMU
audio: start
username@10.0.0.44: Call in-progress: sip:0123456789@10.0.0.44
call: update media
stream: incoming rtp for 'audio' established, receiving from 10.0.0.44:7094
call: got SDP answer (229 bytes)/s)                         [========        ]  [=               ]
call: update media
call: stream start (active=1)
audio: start
username@10.0.0.44: Call established: sip:0123456789@10.0.0.44
audio: [time=11.359] discard old frame (11.359 seconds old)
sip:0123456789@10.0.0.44: session closed: Connection reset by peer      ]  [===             ]
alsa: stopping recording thread (default)
alsa: stopping playback thread (default)
sip:username@10.0.0.44: Call with sip:0123456789@10.0.0.44 terminated (duration: 5 secs)
audio: destroyed (started=1)
ctrl_tcp: handle_command:  cmd='hangup', params:'', token=''

ctrl_tcp: handle_command:  cmd='dial', params:'0123456789', token=''
call: alloc with params laddr=10.0.0.40, af=AF_INET, use_rtp=1
call: use_video=0
call: connecting to 'sip:0123456789@10.0.0.44'..
call: SIP Progress: 100 Trying (/)
call: SIP Progress: 183 Session Progress (application/sdp)
call: stream start (active=0)
audio: Set audio encoder: PCMU 8000Hz 1ch
audio: start
alsa: reset: srate=8000, ch=1, num_frames=160, pcmfmt=S16_LE
alsa: recording started (default) format=S16LE
audio: source started with sample format S16LE
audio: Set audio decoder: PCMU 8000Hz 1ch
audio: start
alsa: reset: srate=8000, ch=1, num_frames=160, pcmfmt=S16_LE
alsa: playback started (default)
audio: player started with sample format S16LE
audio tx pipeline:        alsa ---> vumeter ---> PCMU
audio rx pipeline:        alsa <--- vumeter <--- PCMU
audio: start
username@10.0.0.44: Call in-progress: sip:0123456789@10.0.0.44
call: update media
stream: incoming rtp for 'audio' established, receiving from 10.0.0.44:7078
call: got SDP answer (231 bytes)/s)                         [======          ]  [=               ]
call: update media
call: stream start (active=1)
audio: start
username@10.0.0.44: Call established: sip:0123456789@10.0.0.44
audio: [time=4.559] discard old frame (4.559 seconds old)
sip:0123456789@10.0.0.44: session closed: Connection reset by peer      ]  [===             ]
alsa: stopping recording thread (default)
alsa: stopping playback thread (default)
sip:username@10.0.0.44: Call with sip:0123456789@10.0.0.44 terminated (duration: 4 secs)
audio: destroyed (started=1)
ctrl_tcp: handle_command:  cmd='hangup', params:'', token=''

ctrl_tcp: handle_command:  cmd='dial', params:'0123456789', token=''
call: alloc with params laddr=10.0.0.40, af=AF_INET, use_rtp=1
call: use_video=0
call: connecting to 'sip:0123456789@10.0.0.44'..
call: SIP Progress: 100 Trying (/)
call: SIP Progress: 183 Session Progress (application/sdp)
call: stream start (active=0)
audio: Set audio encoder: PCMU 8000Hz 1ch
audio: start
alsa: reset: srate=8000, ch=1, num_frames=160, pcmfmt=S16_LE
alsa: recording started (default) format=S16LE
audio: source started with sample format S16LE
audio: Set audio decoder: PCMU 8000Hz 1ch
audio: start
alsa: reset: srate=8000, ch=1, num_frames=160, pcmfmt=S16_LE
alsa: playback started (default)
audio: player started with sample format S16LE
audio tx pipeline:        alsa ---> vumeter ---> PCMU
audio rx pipeline:        alsa <--- vumeter <--- PCMU
audio: start
username@10.0.0.44: Call in-progress: sip:0123456789@10.0.0.44
call: update media
stream: incoming rtp for 'audio' established, receiving from 10.0.0.44:7090
call: got SDP answer (231 bytes)/s)                         [======          ]  [=               ]
call: update media
call: stream start (active=1)
audio: start
username@10.0.0.44: Call established: sip:0123456789@10.0.0.44
audio: [time=3.419] discard old frame (3.419 seconds old)   [======          ]  [                ]
sip:0123456789@10.0.0.44: session closed: Connection reset by peer      ]  [===             ]
alsa: stopping recording thread (default)
alsa: stopping playback thread (default)
sip:username@10.0.0.44: Call with sip:0123456789@10.0.0.44 terminated (duration: 2 secs)
audio: destroyed (started=1)

ctrl_tcp: handle_command:  cmd='dial', params:'0123456789', token=''
call: alloc with params laddr=10.0.0.40, af=AF_INET, use_rtp=1
call: use_video=0
call: connecting to 'sip:0123456789@10.0.0.44'..
call: SIP Progress: 100 Trying (/)
ctrl_tcp: handle_command:  cmd='hangup', params:'', token=''
call: terminate call 'c5fe90c258a8d18e' with sip:0123456789@10.0.0.44
audio: destroyed (started=0)
ctrl_tcp: handle_command:  cmd='hangup', params:'', token=''

ctrl_tcp: handle_command:  cmd='dial', params:'0123456789', token=''
call: alloc with params laddr=10.0.0.40, af=AF_INET, use_rtp=1
call: use_video=0
call: connecting to 'sip:0123456789@10.0.0.44'..
call: SIP Progress: 100 Trying (/)
call: SIP Progress: 183 Session Progress (application/sdp)
call: stream start (active=0)
audio: Set audio encoder: PCMU 8000Hz 1ch
audio: start
alsa: reset: srate=8000, ch=1, num_frames=160, pcmfmt=S16_LE
alsa: recording started (default) format=S16LE
audio: source started with sample format S16LE
audio: Set audio decoder: PCMU 8000Hz 1ch
audio: start
alsa: reset: srate=8000, ch=1, num_frames=160, pcmfmt=S16_LE
alsa: playback started (default)
audio: player started with sample format S16LE
audio tx pipeline:        alsa ---> vumeter ---> PCMU
audio rx pipeline:        alsa <--- vumeter <--- PCMU
audio: start
username@10.0.0.44: Call in-progress: sip:0123456789@10.0.0.44
call: update media
stream: incoming rtp for 'audio' established, receiving from 10.0.0.44:7084
call: got SDP answer (231 bytes)/s)                         [=====           ]  [=               ]
call: update media
call: stream start (active=1)
audio: start
username@10.0.0.44: Call established: sip:0123456789@10.0.0.44
audio: [time=3.200] discard old frame (3.200 seconds old)
sip:0123456789@10.0.0.44: session closed: Connection reset by peer      ]  [===             ]
alsa: stopping recording thread (default)
alsa: stopping playback thread (default)
sip:username@10.0.0.44: Call with sip:0123456789@10.0.0.44 terminated (duration: 1 min 32 secs)
audio: destroyed (started=1)

**Comment by Bettman66** [comment]
Ok, schau ich mir an.

**Comment by Bettman66** [comment]
Teste bitte die v2.1.4, danke.

**Comment by mangel8** [comment]
Hab ich installiert und Fehler ist weg. Danke! Funktioniert wieder.
